name: laba_http
description: 'A new Flutter module project.'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.laba_http
    iosBundleIdentifier: com.example.labaHttp
